### ISSUE TITLE
Error in robot localization 

### ISSUE THREAD

**Issue by EmimaJiva** [RobotnikIstobalAI2/rb_theron_sim#4]
@ggari-robotnik @sandra-Robotnik The docker image **rb-theron-gazebo-noetic-0.1.0**  uploaded in the repository [dockerhub](https://hub.docker.com/r/robotnik/robotnik-simulations/tags) has been used. 
When the robots move, they lose their location, as can be seen in the following image. 

![Captura de pantalla de 2024-02-15 09-30-47](https://github.com/RobotnikIstobalAI2/rb_theron_sim/assets/121794419/1fc68e93-5713-48a0-8955-6db4725b33a4)

**Comment by sandra-Robotnik** [comment]
@EmimaJiva, Is the problem when they move and/or when they stay idle for some time?
Can you please record a video?

**Comment by EmimaJiva** [comment]
@ggari-robotnik @sandra-Robotnik The problem is both if they move and if they don't move. Once they are lost, they are no longer well located.

https://github.com/RobotnikIstobalAI2/rb_theron_sim/assets/121794419/b1d9fdc9-8fcc-4e4a-a66a-ee7231ddc13f

**Comment by sandra-Robotnik** [comment]
@EmimaJiva , Our experts require that you provide us with a video of the moment when the robots get lost so that they can analyze it. Can you record a video which shows this?

**Comment by sandra-Robotnik** [comment]
@EmimaJiva , and can you record a rosbag of the moment when the robots get lost?

**Comment by EmimaJiva** [comment]
@sandra-Robotnik The file of the recording is large and I cannot upload it here, I will send it to you by upv exchange.

**Comment by EmimaJiva** [comment]
@sandra-Robotnik Did you receive the file?

**Comment by EmimaJiva** [comment]
@sandra-Robotnik Sorry, I sent you a bad file. Now I send you the good one.

The moment when the robot is lost is not always the same, sometimes it is lost early, sometimes it takes longer to get lost. But it always ends up getting lost.

**Comment by EmimaJiva** [comment]
@sandra-Robotnik Did you receive the correct file?

**Comment by ggari-robotnik** [comment]
@EmimaJiva we just sent you a Google drive link, were you can place the rosbag there. We have problems with microsoft platforms. You should have received a notification email on your account

**Comment by EmimaJiva** [comment]
@ggari-robotnik @sandra-Robotnik I have added another video and the rosbag in the Drive.

**Comment by sandra-Robotnik** [comment]
@EmimaJiva Our experts suspect that it could be related to a physical drift that it is pretty common on some robots in Gazebo. This drift can happen with the robot moving or idle.

For our experts it would be easier to check what is happening by seeing the simulation. So, I will send you an email to arrange a meeting.

**Comment by EmimaJiva** [comment]
@sandra-Robotnik Okay

**Comment by EmimaJiva** [comment]
@ggari-robotnik @sandra-Robotnik As your expert told me, I try to test different commits from the [rb_theron_common](https://github.com/RobotnikAutomation/rb_theron_common) repository of RobotnikAutomation. For this I modify the [rb_theron_sim.repos](https://github.com/RobotnikIstobalAI2/rb_theron_sim/blob/noetic-devel/repos/rb_theron_sim.repos.yaml) file and put the commit as you can see in the figure.
![change commit](https://github.com/RobotnikIstobalAI2/rb_theron_sim/assets/121794419/bb845237-8dea-4cad-aebc-f60b69b45d5f)
But when I build the new image, I get the following error:
![error change commit](https://github.com/RobotnikIstobalAI2/rb_theron_sim/assets/121794419/06301e98-d2cf-4650-8a5e-50cdf46dec94)
Can you tell me how to fix it? I will try to fix it but if you have the answer it would be faster.

**Comment by ggari-robotnik** [comment]
Try changing this here:
[rb_theron_sim.repos.yaml](https://github.com/RobotnikIstobalAI2/rb_theron_sim/blob/noetic-devel/repos/rb_theron_sim.repos.yaml)
```yaml
  src/rb_theron_common:
    type: git
    # url: https://github.com/RobotnikAutomation/rb_theron_common
    url: https://github.com/RobotnikIstobalAI2/rb_theron_common.git
    version: noetic-devel
```

or with explicit commit:
```yaml
  src/rb_theron_common:
    type: git
    # url: https://github.com/RobotnikAutomation/rb_theron_common
    url: https://github.com/RobotnikIstobalAI2/rb_theron_common.git
    version: e45f9884f6f0c6eb61063f3741c154d2fd9b7eee
```
